// File generated by the BNF Converter (bnfc 2.9.4).

package Syntax.normal.Absyn;

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Syntax.normal.Absyn.BoolType p, A arg);
    public R visit(Syntax.normal.Absyn.IntType p, A arg);
    public R visit(Syntax.normal.Absyn.FunType p, A arg);

  }

}
