// File generated by the BNF Converter (bnfc 2.9.4).

package Syntax.normal;

/** All Visitor */

public interface AllVisitor<R,A> extends
  Syntax.normal.Absyn.Program.Visitor<R,A>,
  Syntax.normal.Absyn.Expr.Visitor<R,A>,
  Syntax.normal.Absyn.Type.Visitor<R,A>
{}
