// File generated by the BNF Converter (bnfc 2.9.4).

package Syntax.nameless;

/** All Visitor */

public interface AllVisitor<R,A> extends
  Syntax.nameless.Absyn.Program.Visitor<R,A>,
  Syntax.nameless.Absyn.Expr.Visitor<R,A>,
  Syntax.nameless.Absyn.Type.Visitor<R,A>
{}
