// File generated by the BNF Converter (bnfc 2.9.4).

package Syntax.nameless.Absyn;

public class Abstraction  extends Expr {
  public final Type type_1, type_2;
  public final String ident_;
  public final Expr expr_;
  public Abstraction(Type p1, String p2, Type p3, Expr p4) { type_1 = p1; ident_ = p2; type_2 = p3; expr_ = p4; }

  public <R,A> R accept(Syntax.nameless.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof Syntax.nameless.Absyn.Abstraction) {
      Syntax.nameless.Absyn.Abstraction x = (Syntax.nameless.Absyn.Abstraction)o;
      return this.type_1.equals(x.type_1) && this.ident_.equals(x.ident_) && this.type_2.equals(x.type_2) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.type_1.hashCode())+this.ident_.hashCode())+this.type_2.hashCode())+this.expr_.hashCode();
  }


}
