// File generated by the BNF Converter (bnfc 2.9.4).

package Syntax.nameless.Absyn;

public class IsZero  extends Expr {
  public final Expr expr_;
  public IsZero(Expr p1) { expr_ = p1; }

  public <R,A> R accept(Syntax.nameless.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof Syntax.nameless.Absyn.IsZero) {
      Syntax.nameless.Absyn.IsZero x = (Syntax.nameless.Absyn.IsZero)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
